### ISSUE TITLE
PersonalInviteFactory stores the contract creation code on-chain

### ISSUE THREAD

**Issue by malteish** [corpus-io/tokenize.it-smart-contracts#120]
The PersonalInviteFactory needs only the constructor arguments when deploying an invite. The PersonalInvite's creation code is stored on-chain in the [PersonalInviteFactory](https://github.com/corpus-io/tokenize.it-smart-contracts/blob/main/contracts/PersonalInviteFactory.sol#L83). This approach has pros and cons:

Pro: 
- Platform (and pro-users) do not have to locally compile PersonalInvite when calculating addresses and deploying.
- deployment of PersonalInvite should be a little cheaper, since the transaction is much smaller?
- 
Con: 
- More expensive when deploying PersonalInviteFactory
- A little more transparent (3rd party might have an easier day when trying to analyze PersonalInvite. Is that even a con?

I would like to keep it like it is, but maybe I am missing important aspects?

**Comment by CJentzsch** [comment]
PersonalInviteFactory has no local storage, so as far as I can see, it doesn't store anything.
It is creating the byteCode locally when the function is called, but not on-chain. 

Even if the function would be called on-chain, it does not store anything.

**Comment by CJentzsch** [comment]
If you mean the non-personalized (without constructor arguments) general PersonalInviteCode, then I see no problems with this at all.

The factory is only deployed once, therefore I see no issue with costs either.

**Comment by malteish** [comment]
> If you mean the non-personalized (without constructor arguments) general PersonalInviteCode,
Yes, this is what I was referring to. Since you don't see problems either, we will leave it as-is.
