### ISSUE TITLE
use `transferAndCall` to reduce the investment in continuousFundraising to 1 transaction

### ISSUE THREAD

**Issue by CJentzsch** [corpus-io/tokenize.it-smart-contracts#131]
Currently, the investor has to make two transactions:
* approve the amount in the currency contract
* call`buy` to execute the investment

When the token supports `transferAndCall`, the contracts could be changed to allow for an investment with 1 transaction.

https://github.com/ethereum/EIPs/issues/677

**Comment by CJentzsch** [comment]
EUROC and USDC do not support EIP677, but EURe (Monerium) does.

**Comment by malteish** [comment]
Since EURe is our planned main payment token, extending ContinuousFundraising to be ERC677 compatible is the logical next step.

**Comment by malteish** [comment]
done
