### ISSUE TITLE
add Discounts to FeeSettings

### ISSUE THREAD

**Issue by malteish** [corpus-io/tokenize.it-smart-contracts#135]
# Motivation
Platform wants company to enjoy a fee of 0.2% instead of 1% for a certain time.
# Approach 1: Voucher-handling through new FeeSettings deployment

## What to do
1. Deploy new FeeSettings contract with the desired denominators.
2. Plan fee change to normal fees for end of discount period. 
3. Propose to the company to switch to new feeSettings contract
4. company accepts and enjoys lower fees
5. At end of discount period, platform executes fee change -> discount over.

Optional, but even better: Increase fees to a higher fee at end of discount period and propose changing back to default FeeSettings. This way, the new FeeSettings contract becomes obsolete and does not need to be maintained any longer.

This approach needs no code change in the smart contracts. It can be automated in the web app to enable companies to decide when to start their discount period. Would require some platform cold wallet transactions to make it safer, but could also be completely executed by the relayer instead.

## Summary
works well, let's do this!

# Approach 2: Voucher-handling inside FeeSettings 
The company continues using the same FeeSettings contract others use, but the contract returns different values for this company.

## Requirements
1. Fee getter functions (`tokenFee`, `continuousFundraisingFee`, `personalInviteFee`) need to know which company the request refers to.
2. The FeeSettings contract needs to store if a company is eligible for a discount and apply it in the calculations.
3. If the company is to decide when to activate their voucher: The FeeSettings contract needs to store voucher commitments that can then be activated only by the company they are assigned to.

## Implementation
Requirement 1: Being able to identify the company issuing tokens / receiving payment.
- **token-based: Token address needs to be included in request**
- caller-based identification (who is asking? Which company does this address belong to?) not possible because a company will have any number of private invite contracts
- payment recipient-based identification could be possible
  - requires code changes in ContinuousFundraising and PersonalInvite
  - does not work for direct token minting and employee participation

Requirement 2: Storing who is eligible
- Lookup has to be performed in every call. This makes every call more expensive.
- Mapping would consist of: company id -> (3 x fee denominator or 1 to 3 relative discount values, expiration date)

Requirement 3: commit to discount before activation
- store some hash, allow person providing the source values to activate
- additional authentication required?
## Summary 
Very complex, open questions -> not a great solution yet.

# Approach 3: Everyone pays the same fee on-chain, but some customers get a refund off-chain
Calculations can happen offline and privately, so no information is revealed to third parties. No additional tx cost either.

**Comment by CJentzsch** [comment]
Sounds good.
But now we entering into the phase, where potentially, there is one FeeSettings contract per company

**Comment by malteish** [comment]
decided to work around, see above

**Comment by malteish** [comment]
document this decision for others to find it

**Comment by malteish** [comment]
Decision @CJentzsch and @malteish : choose approach 3

**Comment by malteish** [comment]
updated docs accordingly
