### ISSUE TITLE
Dividend distribution

### ISSUE THREAD

**Issue by malteish** [corpus-io/tokenize.it-smart-contracts#179]
# Motivation
A token creator might want/have to distribute dividends to token holders. Typically, this is done by giving token holders the option to claim their dividend. Avoiding double claims requires a snapshot.

# Solutions
## Off-chain
1. Take snapshot of address balances at certain block
2. Generate merkle tree 
3. Store merkle root in distribution contract
4. Offer tool that helps users to generate a proof, which can be used to claim their share from the distribution contract

## On-chain 
This requires extending the token with the [ERC20Snapshot](https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20Snapshot) feature.
1. Take snapshot on-chain (someone could front-run this transaction! E.g.: buy as many tokens as possible before snapshot, sell immediately after snapshot.)
2. Create distribution contract that queries `token.balanceOfAt(...)` to determine eligibility.

**Comment by malteish** [comment]
I lean towards the off-chain solution because ERC20Snapshot makes every single transfer more expensive:
```
    // Update balance and/or total supply snapshots before the values are modified. This is implemented
    // in the _beforeTokenTransfer hook, which is executed for _mint, _burn, and _transfer operations.
    function _beforeTokenTransfer(address from, address to, uint256 amount) internal virtual override {
        super._beforeTokenTransfer(from, to, amount);

        if (from == address(0)) {
            // mint
            _updateAccountSnapshot(to);
            _updateTotalSupplySnapshot();
        } else if (to == address(0)) {
            // burn
            _updateAccountSnapshot(from);
            _updateTotalSupplySnapshot();
        } else {
            // transfer
            _updateAccountSnapshot(from);
            _updateAccountSnapshot(to);
        }
    }
```

**Comment by CJentzsch** [comment]
We are not the first ones to have this problem.
How have others solved this problem practically?

May ba have a look at the Aragon DAO framework, or DAO stack, on how they have done this.

Another idea:
When claiming dividends from the deposit contract, one has to send the tokens to the contract, and they stay there locked until the dividend-pay-out-period is over.

Token remain freely transferrable, and if one chooses to get the dividends towards the end of the period, the lock-up period is rather short.

**Comment by malteish** [comment]
A closer look into ERC20Snapshot revealed this.

# Ease of use
Integration is a breeze

# Gas Overhead
Gas costs rise significantly.

![grafik](https://github.com/corpus-io/tokenize.it-smart-contracts/assets/102788938/ad16a5c6-35de-42c5-8bb5-99daceede545)

Some tests I created for these occasions to check gas cost for simple default transactions:
```bash
testSimpleTransfer() (gas: 7461 (13.401%)) 
test10Transfers() (gas: 20610 (19.926%)) 
testIncreaseAllowance(uint256,uint256) (gas: 13126 (9.332%)) 
testSimpleTransferFrom() (gas: 7439 (12.737%)) 
```
Token transfers cost roughly 20% more with the snapshot extension!

Full gas comparison before and after snapshot integration:
```bash
testFailNotOwner(address) (gas: 0 (0.000%)) 
testFailNotOwnerRemove(address) (gas: 0 (0.000%)) 
testOwner() (gas: 0 (0.000%)) 
testRemove(address) (gas: 0 (0.000%)) 
testSet() (gas: 0 (0.000%)) 
testSet2() (gas: 0 (0.000%)) 
testSetEvent(address,uint256) (gas: 0 (0.000%)) 
testSetFuzzingAddress(address) (gas: 0 (0.000%)) 
testSetFuzzingValue(uint256) (gas: 0 (0.000%)) 
testConstructorHappyCase() (gas: 0 (0.000%)) 
testConstructorWithAddress0() (gas: 0 (0.000%)) 
testFailOverflow() (gas: 0 (0.000%)) 
testFailPaused() (gas: 0 (0.000%)) 
testFailUnderflow() (gas: 0 (0.000%)) 
testFailUnpauseAfterDelay() (gas: 0 (0.000%)) 
testFailUnpauseImmediatelyAfterPausing() (gas: 0 (0.000%)) 
testFailUpdateCurrencyAndPriceNotPaused() (gas: 0 (0.000%)) 
testFailUpdateCurrencyReceiverNotPaused() (gas: 0 (0.000%)) 
testFailUpdateMaxAmountOfTokenToBeSoldNotPaused() (gas: 0 (0.000%)) 
testFailUpdateMaxAmountPerBuyerNotPaused() (gas: 0 (0.000%)) 
testFailUpdateMinAmountPerBuyerNotPaused() (gas: 0 (0.000%)) 
testLogicContractCreation() (gas: 0 (0.000%)) 
testRevertsOnOverflow(uint256,uint256) (gas: 0 (0.000%)) 
testTransferOwnership(address) (gas: 0 (0.000%)) 
testUnpauseAfterDelayAnd1Sec() (gas: 0 (0.000%)) 
testUnpauseAfterSetCurrencyAndTokenPrice() (gas: 0 (0.000%)) 
testUnpauseAfterSetCurrencyReceiver() (gas: 0 (0.000%)) 
testUnpauseAfterSetMaxAmountOfTokenToBeSold() (gas: 0 (0.000%)) 
testUnpauseAfterSetMaxAmountPerBuyer() (gas: 0 (0.000%)) 
testUnpauseAfterSetMinAmountPerBuyer() (gas: 0 (0.000%)) 
testUnpauseTooSoonAfterSetCurrencyAndTokenPrice(uint128,uint32,uint32,uint256) (gas: 0 (0.000%)) 
testUnpauseTooSoonAfterSetCurrencyReceiver(uint128,uint32,uint32,address) (gas: 0 (0.000%)) 
testUnpauseTooSoonAfterSetMaxAmountOfTokenToBeSold(uint128,uint32,uint32) (gas: 0 (0.000%)) 
testUnpauseTooSoonAfterSetMaxAmountPerBuyer(uint128,uint32,uint32,uint256) (gas: 0 (0.000%)) 
testUnpauseTooSoonAfterSetMinAmountPerBuyer(uint128,uint32,uint32,uint256) (gas: 0 (0.000%)) 
testUpdateCurrencyAndPricePaused(uint256) (gas: 0 (0.000%)) 
testUpdateCurrencyReceiverPaused() (gas: 0 (0.000%)) 
testUpdateMaxAmountOfTokenToBeSoldPaused(uint256) (gas: 0 (0.000%)) 
testUpdateMaxAmountPerBuyerPaused(uint256) (gas: 0 (0.000%)) 
testUpdateMinAmountPerBuyerPaused(uint256) (gas: 0 (0.000%)) 
testAddressPrediction(bytes32,address,address,address,uint256,uint256,uint256,uint256,address,address) (gas: 0 (0.000%)) 
testInitialization(bytes32,address,address,address,uint256,uint256,uint256,uint256,address,address) (gas: 0 (0.000%)) 
testPausing(address,address) (gas: 0 (0.000%)) 
testCalculate0FeesForAmountLessThanUINT256_MAX(uint256,uint256,uint256,uint256) (gas: 0 (0.000%)) 
testCalculate0FeesForAmountUINT256_MAX(uint256,uint256,uint256) (gas: 0 (0.000%)) 
testCalculateProperFees(uint256,uint256,uint256,uint256) (gas: 0 (0.000%)) 
testERC165IsAvailable() (gas: 0 (0.000%)) 
testEnforceContinuousFundraisingFeeDenominatorRangeInFeeChanger(uint8) (gas: 0 (0.000%)) 
testEnforceFeeChangeDelayOnIncrease(uint256,uint256,uint256) (gas: 0 (0.000%)) 
testEnforceFeeDenominatorRangeInConstructor(uint8) (gas: 0 (0.000%)) 
testEnforcePersonalInviteFeeDenominatorRangeInFeeChanger(uint8) (gas: 0 (0.000%)) 
testEnforceTokenFeeDenominatorRangeInFeeChanger(uint8) (gas: 0 (0.000%)) 
testExecuteFeeChangeProperly(uint256,uint256,uint256,uint256) (gas: 0 (0.000%)) 
testExecuteFeeChangeTooEarly(uint256,uint256,uint256) (gas: 0 (0.000%)) 
testFeeCollector0FailsInConstructor() (gas: 0 (0.000%)) 
testFeeCollector0FailsInSetter() (gas: 0 (0.000%)) 
testIFeeSettingsV1IsAvailable() (gas: 0 (0.000%)) 
testIFeeSettingsV2IsAvailable() (gas: 0 (0.000%)) 
testNonsenseInterfacesAreNotAvailable(bytes4) (gas: 0 (0.000%)) 
testReduceFeeImmediately(uint256,uint256,uint256) (gas: 0 (0.000%)) 
testSetFeeInConstructor(uint8,uint8) (gas: 0 (0.000%)) 
testSetFeeTo0Immediately() (gas: 0 (0.000%)) 
testSetFeeToXFrom0Immediately() (gas: 0 (0.000%)) 
testUpdateFeeCollectors(address,address,address) (gas: 0 (0.000%)) 
testManuallyVerifyInterfaceID() (gas: 0 (0.000%)) 
testAnyoneCanTriggerPayout(address) (gas: 0 (0.000%)) 
testFixedSplit() (gas: 0 (0.000%)) 
testLockingFunds() (gas: 0 (0.000%)) 
testMultiplePayments() (gas: 0 (0.000%)) 
testVariableSplit(uint8,uint8,uint128) (gas: 0 (0.000%)) 
testAllowList0() (gas: 0 (0.000%)) 
testFailMintAllowanceUsed(uint256) (gas: 0 (0.000%)) 
testFailSetRequirements() (gas: 0 (0.000%)) 
testFailSetRequirementsAdmin() (gas: 0 (0.000%)) 
testFailSetRequirementsWrongRole() (gas: 0 (0.000%)) 
testFailSetRequirementsX(address) (gas: 0 (0.000%)) 
testFeeSettings0() (gas: 0 (0.000%)) 
testFeeSettingsNoERC165() (gas: 0 (0.000%)) 
testTransferFrom0(address) (gas: 0 (0.000%)) 
testAddressPrediction(bytes32,address,address,uint256,string,string) (gas: 0 (0.000%)) 
testFeeSettingsUpdateRevertsWhenContractFailsERC165Check() (gas: 0 (0.000%)) 
testSuggestNewFeeSettings0() (gas: 0 (0.000%)) 
testSuggestNewFeeSettingsFeeCollector() (gas: 0 (0.000%)) 
testSuggestNewFeeSettingsWrongCaller(address) (gas: 0 (0.000%)) 
testUpdateAllowList0() (gas: 0 (0.000%)) 
testDeployVestingWallet(uint256,address,uint64,uint64) (gas: 0 (0.000%)) 
testWalletVestsAsExpected(uint256,address,uint64,uint64,uint256) (gas: 0 (0.000%)) 
testSecondDeploymentFails(bytes32,address,address,uint256,uint256,uint256,uint256,address,address) (gas: 28 (0.000%)) 
testSecondDeploymentFails(bytes32,address,address,uint256,string,string) (gas: 93 (0.000%)) 
testAcceptWrongFeeSettings() (gas: -22 (-0.001%)) 
testReentrancy() (gas: 43 (0.002%)) 
testAcceptFeeCollectorInsteadOfFeeSettings(address) (gas: -22 (-0.002%)) 
testInitialization(string,string,address,address,uint256) (gas: -49 (-0.003%)) 
testGrantRole(address) (gas: -110 (-0.007%)) 
testDecreaseAllowance(uint256,uint256) (gas: 4 (0.009%)) 
testRevertOnOverflow(uint256,uint256) (gas: -22 (-0.012%)) 
testUpdateAllowList() (gas: -44 (-0.012%)) 
testSuggestNewFeeSettings(address) (gas: 176 (0.016%)) 
testFailBeforeTokenTransferRequirementsNotfulfilled() (gas: -22 (-0.018%)) 
testAcceptNewFeeSettings(address) (gas: 198 (0.018%)) 
testFeeCollectorCanNotAlwaysBuy() (gas: -22 (-0.022%)) 
testFailBeforeTokenTransferRequirements1() (gas: -22 (-0.023%)) 
testFailBurn0() (gas: -21 (-0.039%)) 
testDeployerDoesNotGetRole() (gas: -176 (-0.041%)) 
testSetRequirements(uint256) (gas: -22 (-0.047%)) 
testFailZeroAllowanceMint(uint256) (gas: 23 (0.052%)) 
testBuyTooMuch() (gas: 43 (0.053%)) 
testBuyTooLittle() (gas: 43 (0.055%)) 
testExceedMintingAllowance() (gas: 154 (0.069%)) 
testFailAdmin2() (gas: -22 (-0.100%)) 
testFailAdmin() (gas: -22 (-0.100%)) 
testSetRoleDefaultAdmin() (gas: -44 (-0.102%)) 
testGrantAllowance() (gas: 45 (0.127%)) 
testAcceptFeeSettings0() (gas: -22 (-0.131%)) 
testMintAllower(address) (gas: -22 (-0.150%)) 
testIsNotAdmin(address) (gas: -22 (-0.151%)) 
testAdmin() (gas: 23 (0.157%)) 
testSetUp() (gas: 46 (0.158%)) 
testMinterAdmin() (gas: -22 (-0.191%)) 
testSetRoleMintallower() (gas: -44 (-0.213%)) 
testSetRolePauser() (gas: -44 (-0.213%)) 
testSetRoleRequirements() (gas: -44 (-0.214%)) 
testSeveralContractsOneDomainSeparator() (gas: 10508 (0.226%)) 
testBuyWithLocalForwarder() (gas: 10661 (0.251%)) 
testFee0() (gas: 7516 (0.282%)) 
testSetRoleTransferer() (gas: -88 (-0.315%)) 
testSetRoleBurner() (gas: -66 (-0.320%)) 
testVariousFees(uint256,uint256) (gas: 10792 (0.402%)) 
testVaryDecimals() (gas: 259008 (0.408%)) 
testRoundsUp(uint256,uint256) (gas: 7538 (0.410%)) 
testDecimals() (gas: 43 (0.523%)) 
testPausing(address,address) (gas: 11373 (0.765%)) 
testPersonalInviteWithTimeLock(bytes32,uint64,uint64,uint64) (gas: 17373 (1.178%)) 
testRoundFixedExample1() (gas: 7889 (1.242%)) 
testRoundFixedExample0() (gas: 7889 (1.242%)) 
testRoundUpAnything(uint256,uint256) (gas: 7846 (1.318%)) 
testRoundUp0() (gas: 7846 (1.321%)) 
testTimeLock() (gas: 15518 (1.622%)) 
testAcceptDeal(uint256) (gas: 11122 (1.797%)) 
testAcceptWithDifferentTokenReceiver(uint256) (gas: 11034 (1.814%)) 
testlaunchCompanyAndInvestViaContinuousFundraisingWithLocalForwarder() (gas: 213567 (2.160%)) 
testBuy1BitRoundsUp() (gas: 7407 (2.625%)) 
testMultipleAddressesBuyForOneReceiver() (gas: 10683 (2.756%)) 
testlaunchCompanyAndInvestViaPersonalInviteWithLocalForwarder() (gas: 213567 (2.805%)) 
testBuyAndMintToDifferentAddress() (gas: 10683 (3.050%)) 
testMultiplePeopleBuyTooMuch() (gas: 15366 (3.334%)) 
testBuyAnyAmountRoundsUp(uint256) (gas: 10683 (3.430%)) 
testBuyHappyCase(uint256) (gas: 10815 (3.540%)) 
testCorrectAccounting() (gas: 20049 (3.592%)) 
testUpdateSettingsWithLocalForwarder(uint256) (gas: 202885 (3.773%)) 
testFailTransferPause() (gas: 11978 (3.843%)) 
testTransferUnpaused() (gas: 11956 (3.941%)) 
testMintWithLocalForwarder(uint256) (gas: 213503 (3.959%)) 
testBuySmallAmountAfterInitialInvestment() (gas: 13542 (4.034%)) 
testDeployContract(uint256) (gas: 26202 (4.056%)) 
testBeforeTokenTransferRequirementsOverfulfilled() (gas: 7254 (4.057%)) 
testBeforeTokenTransferRequirements2() (gas: 10583 (4.164%)) 
testFailSetAllowanceTo0BeforeResetting() (gas: 10596 (4.448%)) 
testExceedMintingAllowance() (gas: 10641 (4.547%)) 
testFeeCollectorCanAlwaysReceiveFee() (gas: 10530 (5.326%)) 
testPermitWithClone(string,string,address,uint256,uint256,address,address) (gas: 36423 (5.477%)) 
testLoseAndGainRequirements() (gas: 16603 (6.107%)) 
testBeforeTokenTransfer() (gas: 10605 (6.495%)) 
testLogicContractCreation() (gas: 202952 (6.649%)) 
testPermit(uint256,uint256) (gas: 7462 (6.813%)) 
testBurnWithRequirements(uint256) (gas: 9607 (7.471%)) 
testBurnSimple(uint256) (gas: 10885 (8.184%)) 
testSetUpMinter(uint256,uint256) (gas: 10553 (8.269%)) 
testTransferWith0Requirements() (gas: 13991 (8.522%)) 
testMintOnce(uint256) (gas: 10574 (8.673%)) 
testMintAllowerDoesNotNeedAllowance(uint256) (gas: 10574 (9.028%)) 
testTransferTo0(address) (gas: 10640 (9.148%)) 
testIncreaseAllowance(uint256,uint256) (gas: 13126 (9.332%)) 
testSimpleTransferFrom() (gas: 7439 (12.737%)) 
testMintAgain(uint256,uint256) (gas: 73511 (13.217%)) 
testSimpleTransfer() (gas: 7461 (13.401%)) 
testMint0() (gas: 7254 (13.893%)) 
testBurn0() (gas: 8654 (16.864%)) 
test10Transfers() (gas: 20610 (19.926%)) 
testFailTransfer() (gas: 11461 (36.747%)) 
Overall gas change: 1946734 (0.000%)
```

**Comment by malteish** [comment]
I did some further research because we find it hard to believe that a transfer with ERC20Snapshot consumes almost 10k gas more.
The extension is active in the `_beforeTokenTransfer()` Hook (see [source](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/5bc59992591b84bba18dc1ac46942f1886b30ccd/contracts/token/ERC20/extensions/ERC20SnapshotUpgradeable.sol#L129)), and does `_updateAccountSnapshot()` twice (among other things).
This is the [source code](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/5bc59992591b84bba18dc1ac46942f1886b30ccd/contracts/token/ERC20/extensions/ERC20SnapshotUpgradeable.sol#L174C4-L188C6) of  `_updateAccountSnapshot()`:
```solidity
 function _updateAccountSnapshot(address account) private {
        _updateSnapshot(_accountBalanceSnapshots[account], balanceOf(account));
    }

    function _updateSnapshot(Snapshots storage snapshots, uint256 currentValue) private {
        uint256 currentId = _getCurrentSnapshotId();
        if (_lastSnapshotId(snapshots.ids) < currentId) {
            snapshots.ids.push(currentId);
            snapshots.values.push(currentValue);
        }
    }

    function _getCurrentSnapshotId() internal view virtual returns (uint256) {
        return _currentSnapshotId.current();
    }

    function _lastSnapshotId(uint256[] storage ids) private view returns (uint256) {
        if (ids.length == 0) {
            return 0;
        } else {
            return ids[ids.length - 1];
        }
    }

```

There are two [cold accesses](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a6-sload) when this code snippet is executed for `from`, costing 2100 gas each, which account for a total of 4200 gas difference already:
1. currentId
2. ids.length

Then there are some more warm accesses at 100 gas each (when doing the same checks for `to` and doing other load for both `from` and `to`):
1. currentId
2. ids.length

... to be continued

**Comment by malteish** [comment]
The snapshot extension is not included in openzeppelin contracts upgradeable v5.0

**Comment by malteish** [comment]
[ERC20Votes](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Votes.sol) could potentially be used for building a balance history, too. I need to look more deeply into this.

**Comment by malteish** [comment]
Here are my findings from reading up on ERC20Votes. Most of the magic happens in [Votes](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/governance/utils/Votes.sol) and [Checkpoints](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/Checkpoints.sol).
1. Checkpoints (equivalent to what used to be called Snapshots) are now created automatically whenever tokens are transferred. This must be really expensive, adding over 40k gas on average to every transaction (initializing 2 new slots, one for `to` and one for `from`.
2. Historical balance lookups are now binary searches, which potentially makes them really expensive, too (because they have to read many storage slots).

**Comment by malteish** [comment]
After more research, here are 2 more options:
## ERC20SnapshotVotes 
[Reconstruct the Snapshot behavior with Votes](https://forum.openzeppelin.com/t/erc20snapshot-alternative-in-new-oz-library/38137/12). This allows us to use OZ v5 and still achieve a snapshot-like behavior. It needs more work though, like making it upgradeable and testing it properly.
## Relic Protocol
Relic protocol makes it possible to generate proofs off-chain that can be used on-chain in order to proof certain facts. A fact can be a storage slot at a specific block height, which is what we need for the dividend distribution.
[They have a similar example.](https://github.com/Relic-Protocol/relic-examples/tree/main/airdrop)

Regarding gas cost, I got [this estimate](https://discord.com/channels/1011748641653915708/1167395189455855698/1167616664192417792):

>  
> 
>  1.   each account balance for one token is one fact. More specifically, a single storage slot for a single account is one fact. So if you want to have balances for 100 accounts, there will be 100 facts
> 
>  2.   the gas costs vary slightly depending on the total number of storage costs, because that affects the size of the proof.
> 
> 
> There are also lots of optimizations you may be able to do to reduce gas for example: if all balances you want to prove occur in the same block, then the account storage root for that block can be proved one time, and future proofs can re-use that
> We have a two part blog with some more info about airdrops as well https://medium.com/chainlight/better-airdrops-part-ii-the-details-51b93284a69a is maybe more relevant to you
> [Better Airdrops (Part II-the Details)](https://medium.com/chainlight/better-airdrops-part-ii-the-details-51b93284a69a)
>
> Without any optimizations, proving a storage slot for one account is around 250k gas.
> If you use optimizations like storing the account state root for a block and only proving balances at that block, that can probably be closer to 160k
> 
>  3.   We haven't decided on fees yet. Things have been free for over a year, and we don't have any immediate plans to change that. We hope to eventually turn it on and probably make the fees comparable to the gas costs.
>  
## Merkle tree
We can also still build our own merke tree, which might be more difficult though.

# Comparison
Assuming the SnapshotVotes will consume around 10k gas per transfer, just like the Snapshots do, and that we can proof stuff using Relic Protocol for 160k gas, we can decide which approach is more gas efficient based on this question:
> Is it very likely that our average token holder does a lot more than 16 token transfers between dividend payouts?

With the very common payout schedule of 1 dividend payout per year, the question can be rephrased to:
> Will our average token holder do more than 1 transfer per month?
I think they will not transfer their tokens that often.

Therefore, ERC20Shnapshot seems more gas efficient overall. Also, it is much more transparent, as all accounting takes place on-chain.

**Comment by malteish** [comment]
@CJentzsch and @malteish decided to use the ERC20Snapshot extension. as base for dividend payouts.

**Comment by malteish** [comment]
done
