### ISSUE TITLE
extend FeeSettings

### ISSUE THREAD

**Issue by malteish** [corpus-io/tokenize.it-smart-contracts#188]
* needs additional field to distinguish ContinuousFundraisingFeeReceiver and PrivateOfferFeeReceiver
* maybe for token fee too? -> Likely yes, so the token fees are not split between us and 3rd party.

**Comment by Mariostarship** [comment]
how do i begin tokenize 10M real estate

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
