### ISSUE TITLE
Unify access

### ISSUE THREAD

**Issue by malteish** [corpus-io/tokenize.it-smart-contracts#246]
In `Vesting.sol` we use three ways of accessing a vesting plan's details:

```
// 1
vestings[_id].start

// 2
VestingPlan memory vesting = vestings[_id];
vesting.start

// 3
start(_id)

```

We should decide for 1 or 2. I propose: use 3 by default and 2 if a context accesses many parameters.

**Comment by CJentzsch** [comment]
I agree, it is afer since one is using `internal view` without write access to the parameter.
Only if you nee write access you should use 1
