### ISSUE TITLE
improve natSpec comments for end users

### ISSUE THREAD

**Issue by CJentzsch** [corpus-io/tokenize.it-smart-contracts#97]
Ideally, every operation, esspecially by end users comes with a easy to understand and clear message in their wallet.

E.g. , when investing in company "Meine GmbH" € 100k, it should say:
"Invest <amount> <currency> to buy the token with the name <name> at address: <address>"

NatSpec allows to use the input parameters in the function call for the message.

**Comment by malteish** [comment]
Using radspec, too, now: https://github.com/aragon/radspec
